addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.6")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("com.github.fedragon" % "sbt-todolist" % "0.7")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.5")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.2.1")
